#!/usr/bin/python3
import shelve
import os
import sys
from pathlib import Path
from helper_functions import create_command_list, filter_directories_with_period


def main():
    if len(sys.argv) == 1:
        print(create_command_list())
        return
    home_dir = Path.home()
    command = sys.argv[1]
    shelf = shelve.open("save_file")
    if command == "reset" or command == "add":
        home_dir_list = filter_directories_with_period(os.listdir(home_dir), home_dir)
        list_of_directories_in_home = "list of Directories:\n\n"
        ref_photo_dir = None

        for i in range(len(home_dir_list)):
            list_of_directories_in_home += f"- {home_dir_list[i]}\n"
        ref_photo_dir = input(
            (
                f"{list_of_directories_in_home}Please type in the directory "
                "name that contains the reference\n"
                "image files or create a new one: \n"
            )
        )
        shelf["ref_photo_dir"] = ref_photo_dir
        if not (ref_photo_dir) in home_dir_list:
            os.makedirs(f"{home_dir}/{ref_photo_dir}")
    if command == "current":
        print(f"Current Directory:  {shelf['ref_photo_dir']}")
    if command == "shuffle":
        parent_dir = home_dir / shelf["ref_photo_dir"]
        current_glob_list = filter_directories_with_period(list(parent_dir.glob("*")))
        for item in current_glob_list:
            print(item.name)
    shelf.close()


if __name__ == "__main__":
    main()
