#!/usr/bin/python3
import shelve
import os
import sys
import random
from pathlib import Path
from helper_functions import create_command_list, filter_dirs_with_period, copy_file


def main():
    if len(sys.argv) == 1:
        print(create_command_list())
        return
    home_dir = Path.home()
    command = sys.argv[1]
    shelf = shelve.open("save_file")
    if command == "reset" or command == "add":
        home_dir_list = filter_dirs_with_period(os.listdir(home_dir), home_dir)
        list_of_directories_in_home = "list of Directories:\n\n"
        ref_photo_dir = None

        for i in range(len(home_dir_list)):
            list_of_directories_in_home += f"- {home_dir_list[i]}\n"
        ref_photo_dir = input(
            (
                f"{list_of_directories_in_home}Please type in the directory "
                "name that contains the reference\n"
                "image files or create a new one: \n"
            )
        )
        shelf["ref_photo_dir"] = ref_photo_dir
        if not (ref_photo_dir) in home_dir_list:
            os.makedirs(f"{home_dir}/{ref_photo_dir}")
    if command == "current":
        print(f"Current Directory:  {shelf['ref_photo_dir']}")
    if command == "shuffle":
        image_list = []
        parent_dir = home_dir / shelf["ref_photo_dir"]
        current_glob_list = filter_dirs_with_period(list(parent_dir.glob("*")))
        previous_ref_dir = parent_dir / "gesture-quest-ref"
        previuos_glob = list(previous_ref_dir.glob("*.jpg"))
        for image in previuos_glob:
            os.unlink(image)
            print("list :", image)
        # print(current_glob_list)
        for item in current_glob_list:
            if item.name == "Obscura Reference Sampler":
                glob_list = filter_dirs_with_period(list(item.glob("*.jpg")))
                for image in glob_list:
                    image_list.append(image)
                for i in range(int(sys.argv[2]) + 1):
                    random_index = random.randrange(0, len(image_list))
                    print(random_index)
                    copy_file(
                        image_list[random_index], parent_dir / "gesture-quest-ref"
                    )

    shelf.close()


if __name__ == "__main__":
    main()
